### ISSUE TITLE
No output on @output_script

### ISSUE THREAD

**Issue by testagnostic** [hotmit/mysql-sp-audit#2]
Nice script. which we required as it is. Please help.

call zsp_generate_audit( 'mydbname', 'wow_users', @output_script, @output_errors);

Please let me know. I don't find any tables/views created running these procedure.

**Comment by hotmit** [comment]
Sorry for the delay, but some how I never got notified by this issue entry. In order to see the output you have to select the the variables yourself.

```sql
CALL zsp_generate_audit( 'mydbname', 'wow_users', @output_script, @output_errors);
SELECT @output_script, @output_errors;
```
